// ============================================================
// RADMS Mock Data - Data simulasi untuk development
// ============================================================

export const AIRPORTS = {
  'bandara-hassanuddin': {
    id: 'bandara-hassanuddin',
    name: 'Bandara Sultan Hasanuddin',
    city: 'Makassar',
    province: 'Sulawesi Selatan',
    iata: 'UPG',
    lat: -5.077333,
    lng: 119.546389,
    geofenceRadius: 500,
    address: 'Jl. Bandara Hasanuddin, Maros, Sulawesi Selatan 90552',
    phone: '+62 411 555 1234',
    terminals: ['Terminal Domestik', 'Terminal Internasional'],
    zones: [
      { id: 'Z1', name: 'Zona Kedatangan Domestik', lat: -5.0773, lng: 119.5462 },
      { id: 'Z2', name: 'Zona Kedatangan Internasional', lat: -5.0778, lng: 119.5468 },
      { id: 'Z3', name: 'Zona Keberangkatan', lat: -5.0768, lng: 119.5457 },
      { id: 'Z4', name: 'Zona Parkir Taksi', lat: -5.0780, lng: 119.5472 },
    ],
  },
  'bandara-sultan-thaha': {
    id: 'bandara-sultan-thaha',
    name: 'Bandara Sultan Thaha',
    city: 'Jambi',
    province: 'Jambi',
    iata: 'DJB',
    lat: -1.6318503590205926,
    lng: 103.6438520018439,
    geofenceRadius: 500,
    address: 'Jl. Sultan Thaha, Jambi 36137',
    phone: '+62 741 555 1234',
    terminals: ['Terminal Domestik'],
    zones: [
      { id: 'Z1', name: 'Zona Kedatangan', lat: -1.6318, lng: 103.6439 },
      { id: 'Z2', name: 'Zona Keberangkatan', lat: -1.6310, lng: 103.6433 },
      { id: 'Z3', name: 'Zona Parkir Taksi', lat: -1.6325, lng: 103.6446 },
    ],
  },
  'bandara-hang-nadim': {
    id: 'bandara-hang-nadim',
    name: 'Bandara Internasional Hang Nadim',
    city: 'Batam',
    province: 'Kepulauan Riau',
    iata: 'BTH',
    lat: 1.122722,
    lng: 104.114000,
    geofenceRadius: 500,
    address: 'Jl. Hang Nadim, Batam 29432',
    phone: '+62 778 555 1234',
    terminals: ['Terminal Domestik', 'Terminal Internasional'],
    zones: [
      { id: 'Z1', name: 'Zona Kedatangan', lat: 1.1227, lng: 104.1140 },
      { id: 'Z2', name: 'Zona Keberangkatan', lat: 1.1220, lng: 104.1133 },
      { id: 'Z3', name: 'Zona Parkir Taksi', lat: 1.1233, lng: 104.1147 },
    ],
  },
  'bandara-sepinggan': {
    id: 'bandara-sepinggan',
    name: 'Bandara Internasional Sultan Aji Muhammad Sulaiman',
    city: 'Balikpapan',
    province: 'Kalimantan Timur',
    iata: 'BPN',
    lat: -1.260194,
    lng: 116.900083,
    geofenceRadius: 500,
    address: 'Jl. Marsma Iswahyudi, Balikpapan 76115',
    phone: '+62 542 555 1234',
    terminals: ['Terminal Domestik', 'Terminal Internasional'],
    zones: [
      { id: 'Z1', name: 'Zona Kedatangan', lat: -1.2602, lng: 116.9001 },
      { id: 'Z2', name: 'Zona Keberangkatan', lat: -1.2594, lng: 116.8994 },
      { id: 'Z3', name: 'Zona Parkir Taksi', lat: -1.2609, lng: 116.9008 },
    ],
  },
  'bandara-sam-ratulangi': {
    id: 'bandara-sam-ratulangi',
    name: 'Bandara Internasional Sam Ratulangi',
    city: 'Manado',
    province: 'Sulawesi Utara',
    iata: 'MDC',
    lat: 1.543222,
    lng: 124.922111,
    geofenceRadius: 500,
    address: 'Jl. AA Maramis, Manado 95371',
    phone: '+62 431 555 1234',
    terminals: ['Terminal Domestik', 'Terminal Internasional'],
    zones: [
      { id: 'Z1', name: 'Zona Kedatangan', lat: 1.5432, lng: 124.9221 },
      { id: 'Z2', name: 'Zona Keberangkatan', lat: 1.5424, lng: 124.9214 },
      { id: 'Z3', name: 'Zona Parkir Taksi', lat: 1.5440, lng: 124.9228 },
    ],
  },
  'bandara-sultan-syarif': {
    id: 'bandara-sultan-syarif',
    name: 'Bandara Internasional Sultan Syarif Kasim II',
    city: 'Pekanbaru',
    province: 'Riau',
    iata: 'PKU',
    lat: 0.464944,
    lng: 101.448500,
    geofenceRadius: 500,
    address: 'Jl. Pramuka, Pekanbaru 28284',
    phone: '+62 761 555 1234',
    terminals: ['Terminal Domestik', 'Terminal Internasional'],
    zones: [
      { id: 'Z1', name: 'Zona Kedatangan', lat: 0.4649, lng: 101.4485 },
      { id: 'Z2', name: 'Zona Keberangkatan', lat: 0.4642, lng: 101.4478 },
      { id: 'Z3', name: 'Zona Parkir Taksi', lat: 0.4656, lng: 101.4492 },
    ],
  },
};

// Maps driver.airportId (from Firebase/Google Sheets) to AIRPORTS key
export const AIRPORT_ID_MAP = {
  'ID Rifim Airport Jambi': 'bandara-sultan-thaha',
  'ID Rifim Airport Batam': 'bandara-hang-nadim',
  'ID Rifim Airport Balikpapan': 'bandara-sepinggan',
  'ID Rifim Airport Manado': 'bandara-sam-ratulangi',
  'ID Rifim Airport Pekanbaru': 'bandara-sultan-syarif',
  'ID Rifim Airport Makassar': 'bandara-hassanuddin',
  // fallback keys (short form)
  'jambi': 'bandara-sultan-thaha',
  'batam': 'bandara-hang-nadim',
  'balikpapan': 'bandara-sepinggan',
  'manado': 'bandara-sam-ratulangi',
  'pekanbaru': 'bandara-sultan-syarif',
  'makassar': 'bandara-hassanuddin',
};

/** Resolve a driver.airportId string to an AIRPORTS key */
export function resolveAirportKey(airportId) {
  if (!airportId) return 'bandara-hassanuddin';
  if (AIRPORTS[airportId]) return airportId; // already a valid key
  return AIRPORT_ID_MAP[airportId] || 'bandara-hassanuddin';
}

export const DEFAULT_AIRPORT_ID = 'bandara-hassanuddin';

// Mock driver accounts untuk login
export const MOCK_DRIVERS = [
  {
    id: 'driver-001',
    name: 'Ahmad Syarifuddin',
    phone: '081234567890',
    password: '123456',
    airportId: 'bandara-hassanuddin',
    vehicleType: 'Taksi',
    vehiclePlate: 'DD 1234 AB',
    vehicleModel: 'Toyota Avanza 2022',
    licenseNumber: 'SIM-A-001234567',
    photo: null,
    rating: 4.8,
    totalTrips: 1247,
    joinDate: '2021-03-15',
    status: 'active',
    online: false,
    lat: -5.0614,
    lng: 119.5542,
    speed: 0,
    lastUpdate: new Date().toISOString(),
    verified: true,
  },
  {
    id: 'driver-002',
    name: 'Budi Santoso',
    phone: '082345678901',
    password: '123456',
    airportId: 'bandara-hassanuddin',
    vehicleType: 'Taksi',
    vehiclePlate: 'DD 5678 CD',
    vehicleModel: 'Honda Brio 2023',
    licenseNumber: 'SIM-A-002345678',
    photo: null,
    rating: 4.6,
    totalTrips: 893,
    joinDate: '2022-01-20',
    status: 'active',
    online: true,
    lat: -5.0618,
    lng: 119.5548,
    speed: 0,
    lastUpdate: new Date().toISOString(),
    verified: true,
  },
  {
    id: 'driver-003',
    name: 'Siti Rahmawati',
    phone: '083456789012',
    password: '123456',
    airportId: 'bandara-hassanuddin',
    vehicleType: 'Taksi',
    vehiclePlate: 'DD 9012 EF',
    vehicleModel: 'Daihatsu Xenia 2021',
    licenseNumber: 'SIM-A-003456789',
    photo: null,
    rating: 4.9,
    totalTrips: 2105,
    joinDate: '2020-06-10',
    status: 'active',
    online: true,
    lat: -5.0608,
    lng: 119.5535,
    speed: 5,
    lastUpdate: new Date().toISOString(),
    verified: true,
  },
];

// Mock queue data
export const generateQueueData = (airportId, currentDriverId) => {
  const now = new Date();
  return [
    {
      id: 'driver-003',
      driverId: 'driver-003',
      name: 'Siti Rahmawati',
      vehiclePlate: 'DD 9012 EF',
      queueNumber: 1,
      status: 'CALLED',
      joinedAt: new Date(now.getTime() - 45 * 60000).toISOString(),
      zone: 'Zona Kedatangan Domestik',
    },
    {
      id: 'driver-002',
      driverId: 'driver-002',
      name: 'Budi Santoso',
      vehiclePlate: 'DD 5678 CD',
      queueNumber: 2,
      status: 'WAITING',
      joinedAt: new Date(now.getTime() - 30 * 60000).toISOString(),
      zone: 'Zona Kedatangan Domestik',
    },
    {
      id: 'driver-004',
      driverId: 'driver-004',
      name: 'Rudi Hermawan',
      vehiclePlate: 'DD 3456 GH',
      queueNumber: 3,
      status: 'WAITING',
      joinedAt: new Date(now.getTime() - 20 * 60000).toISOString(),
      zone: 'Zona Kedatangan Domestik',
    },
    {
      id: 'driver-005',
      driverId: 'driver-005',
      name: 'Dewi Lestari',
      vehiclePlate: 'DD 7890 IJ',
      queueNumber: 4,
      status: 'WAITING',
      joinedAt: new Date(now.getTime() - 15 * 60000).toISOString(),
      zone: 'Zona Kedatangan Internasional',
    },
    {
      id: 'driver-006',
      driverId: 'driver-006',
      name: 'Hendra Kusuma',
      vehiclePlate: 'DD 2345 KL',
      queueNumber: 5,
      status: 'WAITING',
      joinedAt: new Date(now.getTime() - 10 * 60000).toISOString(),
      zone: 'Zona Kedatangan Internasional',
    },
    {
      id: currentDriverId || 'driver-001',
      driverId: currentDriverId || 'driver-001',
      name: 'Ahmad Syarifuddin',
      vehiclePlate: 'DD 1234 AB',
      queueNumber: 6,
      status: 'WAITING',
      joinedAt: new Date(now.getTime() - 5 * 60000).toISOString(),
      zone: 'Zona Parkir Taksi',
    },
    {
      id: 'driver-007',
      driverId: 'driver-007',
      name: 'Andi Wijaya',
      vehiclePlate: 'DD 6789 MN',
      queueNumber: 7,
      status: 'WAITING',
      joinedAt: new Date(now.getTime() - 2 * 60000).toISOString(),
      zone: 'Zona Parkir Taksi',
    },
    {
      id: 'driver-008',
      driverId: 'driver-008',
      name: 'Nurul Fadilah',
      vehiclePlate: 'DD 0123 OP',
      queueNumber: 8,
      status: 'WAITING',
      joinedAt: new Date(now.getTime() - 1 * 60000).toISOString(),
      zone: 'Zona Parkir Taksi',
    },
  ];
};

// Mock notifications
export const generateNotifications = () => {
  const now = new Date();
  return [
    {
      id: 'notif-001',
      title: 'Anda Dipanggil!',
      message: 'Nomor antrian Anda #6 telah dipanggil. Segera menuju Zona Kedatangan Domestik.',
      type: 'CALLED',
      targetRole: 'driver',
      read: false,
      createdAt: new Date(now.getTime() - 2 * 60000).toISOString(),
      icon: 'bell',
    },
    {
      id: 'notif-002',
      title: 'Geofence Aktif',
      message: 'Anda telah memasuki area Bandara Sultan Hasanuddin. Nomor antrian #6 telah diberikan.',
      type: 'GEOFENCE',
      targetRole: 'driver',
      read: false,
      createdAt: new Date(now.getTime() - 15 * 60000).toISOString(),
      icon: 'map-pin',
    },
    {
      id: 'notif-003',
      title: 'Pengumuman Sistem',
      message: 'Pemeliharaan sistem akan dilakukan pada hari Minggu, 15 Juni 2025 pukul 02.00-04.00 WITA.',
      type: 'ANNOUNCEMENT',
      targetRole: 'all',
      read: true,
      createdAt: new Date(now.getTime() - 2 * 60 * 60000).toISOString(),
      icon: 'info',
    },
    {
      id: 'notif-004',
      title: 'Perjalanan Selesai',
      message: 'Perjalanan ke Jl. Perintis Kemerdekaan No. 45 telah selesai. Pendapatan: Rp 85.000',
      type: 'COMPLETED',
      targetRole: 'driver',
      read: true,
      createdAt: new Date(now.getTime() - 5 * 60 * 60000).toISOString(),
      icon: 'check-circle',
    },
    {
      id: 'notif-005',
      title: 'Rating Diterima',
      message: 'Penumpang memberikan rating 5 bintang untuk perjalanan terakhir Anda. Terima kasih!',
      type: 'RATING',
      targetRole: 'driver',
      read: true,
      createdAt: new Date(now.getTime() - 6 * 60 * 60000).toISOString(),
      icon: 'star',
    },
    {
      id: 'notif-006',
      title: 'Cuaca Ekstrem',
      message: 'BMKG menginformasikan potensi hujan lebat di wilayah Makassar. Harap berhati-hati saat berkendara.',
      type: 'WEATHER',
      targetRole: 'all',
      read: true,
      createdAt: new Date(now.getTime() - 1 * 24 * 60 * 60000).toISOString(),
      icon: 'cloud-rain',
    },
    {
      id: 'notif-007',
      title: 'Penumpang Baru',
      message: 'Ada penumpang baru menunggu di Terminal B Gate 7. Silakan cek aplikasi.',
      type: 'PASSENGER',
      targetRole: 'driver',
      read: true,
      createdAt: new Date(now.getTime() - 2 * 24 * 60 * 60000).toISOString(),
      icon: 'user',
    },
  ];
};

// Mock pickup history
export const generateHistory = (driverId) => {
  const now = new Date();
  return [
    {
      id: 'trip-001',
      driverId,
      passengerName: 'Rendi Pratama',
      passengerPhone: '08123456789',
      pickupLocation: 'Terminal Kedatangan Domestik, Bandara Sultan Hasanuddin',
      dropoffLocation: 'Hotel Novotel Makassar, Jl. Jend. Sudirman No. 24',
      distance: 18.5,
      duration: 35,
      fare: 95000,
      status: 'COMPLETED',
      queueNumber: 6,
      rating: 5,
      startTime: new Date(now.getTime() - 5 * 60 * 60000).toISOString(),
      endTime: new Date(now.getTime() - 4.4 * 60 * 60000).toISOString(),
      paymentMethod: 'Tunai',
    },
    {
      id: 'trip-002',
      driverId,
      passengerName: 'Maria Santos',
      passengerPhone: '08234567890',
      pickupLocation: 'Terminal Kedatangan Internasional, Bandara Sultan Hasanuddin',
      dropoffLocation: 'Trans Studio Makassar, Jl. AP. Pettarani',
      distance: 22.3,
      duration: 45,
      fare: 120000,
      status: 'COMPLETED',
      queueNumber: 4,
      rating: 4,
      startTime: new Date(now.getTime() - 1 * 24 * 60 * 60000).toISOString(),
      endTime: new Date(now.getTime() - 23.2 * 60 * 60000).toISOString(),
      paymentMethod: 'GoPay',
    },
    {
      id: 'trip-003',
      driverId,
      passengerName: 'Arif Budiman',
      passengerPhone: '08345678901',
      pickupLocation: 'Terminal Kedatangan Domestik, Bandara Sultan Hasanuddin',
      dropoffLocation: 'Makassar Golden Hotel, Jl. Pasar Ikan No. 52',
      distance: 25.1,
      duration: 50,
      fare: 130000,
      status: 'COMPLETED',
      queueNumber: 8,
      rating: 5,
      startTime: new Date(now.getTime() - 2 * 24 * 60 * 60000).toISOString(),
      endTime: new Date(now.getTime() - 47 * 60 * 60000).toISOString(),
      paymentMethod: 'Tunai',
    },
    {
      id: 'trip-004',
      driverId,
      passengerName: 'Fitri Handayani',
      passengerPhone: '08456789012',
      pickupLocation: 'Terminal Kedatangan Domestik, Bandara Sultan Hasanuddin',
      dropoffLocation: 'RS Wahidin Sudirohusodo, Jl. Perintis Kemerdekaan',
      distance: 12.8,
      duration: 28,
      fare: 70000,
      status: 'CANCELLED',
      queueNumber: 3,
      rating: null,
      startTime: new Date(now.getTime() - 3 * 24 * 60 * 60000).toISOString(),
      endTime: new Date(now.getTime() - 71.5 * 60 * 60000).toISOString(),
      paymentMethod: 'Tunai',
      cancelReason: 'Penumpang membatalkan',
    },
    {
      id: 'trip-005',
      driverId,
      passengerName: 'Dian Purnomo',
      passengerPhone: '08567890123',
      pickupLocation: 'Terminal Kedatangan Domestik, Bandara Sultan Hasanuddin',
      dropoffLocation: 'Pantai Losari, Jl. Penghibur, Makassar',
      distance: 28.7,
      duration: 55,
      fare: 145000,
      status: 'COMPLETED',
      queueNumber: 5,
      rating: 5,
      startTime: new Date(now.getTime() - 4 * 24 * 60 * 60000).toISOString(),
      endTime: new Date(now.getTime() - 95 * 60 * 60000).toISOString(),
      paymentMethod: 'OVO',
    },
    {
      id: 'trip-006',
      driverId,
      passengerName: 'Iwan Setiawan',
      passengerPhone: '08678901234',
      pickupLocation: 'Terminal Kedatangan Internasional, Bandara Sultan Hasanuddin',
      dropoffLocation: 'Unhas, Jl. Perintis Kemerdekaan KM 10',
      distance: 15.2,
      duration: 32,
      fare: 82000,
      status: 'COMPLETED',
      queueNumber: 2,
      rating: 4,
      startTime: new Date(now.getTime() - 5 * 24 * 60 * 60000).toISOString(),
      endTime: new Date(now.getTime() - 119.5 * 60 * 60000).toISOString(),
      paymentMethod: 'Tunai',
    },
  ];
};

// Mock online drivers map data
export const generateOnlineDrivers = () => {
  return [
    { id: 'driver-002', name: 'Budi S.', lat: -5.0618, lng: 119.5548, status: 'WAITING', queueNumber: 2 },
    { id: 'driver-003', name: 'Siti R.', lat: -5.0608, lng: 119.5535, status: 'CALLED', queueNumber: 1 },
    { id: 'driver-004', name: 'Rudi H.', lat: -5.0625, lng: 119.5558, status: 'WAITING', queueNumber: 3 },
    { id: 'driver-005', name: 'Dewi L.', lat: -5.0600, lng: 119.5528, status: 'WAITING', queueNumber: 4 },
    { id: 'driver-007', name: 'Andi W.', lat: -5.0630, lng: 119.5542, status: 'WAITING', queueNumber: 7 },
  ];
};
