// Airport reference data — real geographic identifiers used for dropdowns & map
// Runtime stats (driversOnline, queueCount, etc.) come from live Supabase data

export const AIRPORTS = [
  {
    id: 'ID Rifim Airport Batam',
    code: 'BTH',
    name: 'Hang Nadim',
    city: 'Batam',
    province: 'Kepulauan Riau',
    fullName: 'Bandara Internasional Hang Nadim Batam',
    lat: 1.1222699737600552,
    lng: 104.11830538258901,
    radius: 500,
    tz: 'WIB',
    status: 'active',
  },
  {
    id: 'ID Rifim Airport Jambi',
    code: 'DJB',
    name: 'Sultan Thaha',
    city: 'Jambi',
    province: 'Jambi',
    fullName: 'Bandara Sultan Thaha Syaifuddin Jambi',
    lat: -1.6318367703997263,
    lng: 103.64383210805866,
    radius: 500,
    tz: 'WIB',
    status: 'active',
  },
  {
    id: 'ID Rifim Airport Balikpapan',
    code: 'BPN',
    name: 'Sultan Aji Muhammad Sulaiman',
    city: 'Balikpapan',
    province: 'Kalimantan Timur',
    fullName: 'Bandara Sultan Aji Muhammad Sulaiman Sepinggan Balikpapan',
    lat: -1.267625979363085,
    lng: 116.89423472491762,
    radius: 500,
    tz: 'WITA',
    status: 'active',
  },
  {
    id: 'ID Rifim Airport Manado',
    code: 'MDC',
    name: 'Sam Ratulangi',
    city: 'Manado',
    province: 'Sulawesi Utara',
    fullName: 'Bandara Internasional Sam Ratulangi Manado',
    lat: 1.550165772441465,
    lng: 124.9254933960822,
    radius: 500,
    tz: 'WITA',
    status: 'active',
  },
  {
    id: 'ID Rifim Airport Pekanbaru',
    code: 'PKU',
    name: 'Sultan Syarif Kasim II',
    city: 'Pekanbaru',
    province: 'Riau',
    fullName: 'Bandara Sultan Syarif Kasim II Pekanbaru',
    lat: 0.46454514194723073,
    lng: 101.44817503840943,
    radius: 500,
    tz: 'WIB',
    status: 'active',
  },
  {
    id: 'ID Rifim Airport Makassar',
    code: 'UPG',
    name: 'Sultan Hasanuddin',
    city: 'Makassar',
    province: 'Sulawesi Selatan',
    fullName: 'Bandara Internasional Sultan Hasanuddin Makassar',
    lat: -5.074472,
    lng: 119.543889,
    radius: 500,
    tz: 'WITA',
    status: 'active',
  },
  {
    id: 'ID Rifim Batam',
    code: 'BTM',
    name: 'Area Luar Batam',
    city: 'Batam',
    province: 'Kepulauan Riau',
    fullName: 'ID Rifim Batam (Area Luar)',
    lat: 1.1211,
    lng: 104.0402,
    radius: 2000,
    tz: 'WIB',
    status: 'active',
  },
  {
    id: 'ID Rifim Jambi Luar',
    code: 'JBL',
    name: 'Area Luar Jambi',
    city: 'Jambi',
    province: 'Jambi',
    fullName: 'ID Rifim Jambi Luar (Area Luar)',
    lat: -1.6500,
    lng: 103.6300,
    radius: 2000,
    tz: 'WIB',
    status: 'active',
  },
]
